### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by heavenley** [nolanlawson/Catlog#49]
I want to use [Sourcegraph](https://sourcegraph.com) for Catlog code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/nolanlawson/Catlog. (It should only take 30 seconds.)

Thank you!

**Comment by nolanlawson** [comment]
Sorry, I'm probably not going to sign up for this thing. But you are free to fork Catlog and sign up yourself. :)
