### ISSUE TITLE
not working on android 6

### ISSUE THREAD

**Issue by treakiandroid** [nolanlawson/Catlog#55]
Hi, on kitkat it still worked good, but now on marschmellow (android 6) it is asking for root, i am allowing, and than there is only an internety circle of waiting... Plz fix

**Comment by nolanlawson** [comment]
This cannot be fixed: https://nolanlawson.com/2012/09/02/catlog-jives-with-jelly-bean-goes-open-source/

**Comment by treakiandroid** [comment]
my phone is rooted by default (cyanogenmod) and i am able to view logcat from root enabled apps (for example connectbot, add local profile, type in su and then logcat) but catlog dosnt show anything.

so dont understand me wrong i say it isent working even if i have root access and gave it to catlog.

i can try to get you a logcat but i have done that previusly using catlog if you still interested to to fix that
