### ISSUE TITLE
Wonderful program but

### ISSUE THREAD

**Issue by Craftlove** [nolanlawson/Catlog#59]
On my previous device everything worked. 
Fi the settings were accessible. Now that is not the case anymore.
Samsung Galaxy J5 Marshmallow 
Thanks and Cheers

**Comment by ValentinH** [comment]
This blog post might interest you: https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/

**Comment by Craftlove** [comment]
solved it by buying another program


Op maandag 6 maart 2017 om 11:05 schreef Valentin Hervieu:

**Comment by nolanlawson** [comment]
Ironically I predicted exactly this response in my blog post 😜 

In any case yeah this app was designed for older Android; it's hard to access the global context menu on some newer devices

**Comment by ValentinH** [comment]
Indeed, this is a perfect example ^^

**Comment by Craftlove** [comment]
Maybe you can catch up... No hard feelings ;-)  have an older device too 
where I use it. Cheers and good luck


Op maandag 6 maart 2017 om 15:29 schreef Nolan Lawson:

**Comment by Craftlove** [comment]
Edit: On second sight I think this is an arrogant nerd machination one 
two over the innocent client's abc feedback. A shame. So I salute you 
while deleting you everywhere. The hubris. Grow some balls and come to 
the next Platform.
Agree. I started nicely. But you could have apologized as well for not 
overcoming the Slippery Slope.

**Comment by ValentinH** [comment]
WTF

**Comment by Craftlove** [comment]
γνῶθι σεαυτόν


Op maandag 6 maart 2017 om 21:22 schreef Valentin Hervieu:
